<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>dwaslashe-SurvivalCore</name>
    <description>Core for server Survival!</description>

    <groupId>xyz.dwaslashe</groupId>
    <artifactId>dwaslashe-SurvivalCore</artifactId>
    <version>0.1.0-stable</version>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>papi-repo</id>
            <url>http://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>minecraft-libraries</id>
            <name>Minecraft Libraries</name>
            <url>https://libraries.minecraft.net</url>
        </repository>
        <repository>
            <id>sk89q-repo</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>okaeri-repo</id>
            <url>https://storehouse.okaeri.eu/repository/maven-public/</url>
        </repository>
        <repository>
            <id>krypton</id>
            <url>https://repo.kryptonmc.org/releases</url>
        </repository>
        <repository> <!-- for development builds -->
            <id>sonatype-oss-snapshots1</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>minebench-repo</id>
            <url>https://repo.minebench.de/</url>
        </repository>
        <repository>
            <id>quickshop-repo</id>
            <url>https://repo.codemc.io/repository/maven-public/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <!-- This is a temporary reference as the Maven Shade plugin
                that supports Java 16 is not released yet -->
            <id>maven-snapshots</id>
            <url>https://repository.apache.org/content/repositories/snapshots/</url>
        </pluginRepository>
        <pluginRepository>
            <id>krypton</id>
            <url>https://repo.kryptonmc.org/releases</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>

        <!--
        Net Kyori
        -->

        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-minimessage</artifactId>
            <version>4.14.0</version>
        </dependency>

        <!--
        Depends Jar
        -->

        <dependency>
            <groupId>armorequipevent</groupId>
            <artifactId>armorequipevent</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/ArmorEquipEvent-1.7.6.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>paper</groupId>
            <artifactId>paper</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/purpur-1.20.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>authlib</artifactId>
            <version>3.11.49</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/authlib-3.11.49.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>axer.nickanmer</groupId>
            <artifactId>NickNamer</artifactId>
            <version>0.0.1</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/AxerrNicknamer-v1.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>wg.regions</groupId>
            <artifactId>WGRegionsEvent</artifactId>
            <version>0.0.1</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/WGRegionEvents.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>nbt-api</groupId>
            <artifactId>nbt</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/item-nbt-api-plugin-2.9.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.saidora</groupId>
            <artifactId>EconomyManager</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/original-EconomyManager-0.0.1-stable.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.saidora</groupId>
            <artifactId>Economy</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/DeluxeSellwands_Build_33.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.saidora</groupId>
            <artifactId>Ether-API</artifactId>
            <version>0.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/API.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.minecodes</groupId>
            <artifactId>minePlots</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/minePlots-4.3.0-public.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.combat</groupId>
            <artifactId>DeluxeCombats</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/DeluxeCombat v.1.50.8.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>u.drugs</groupId>
            <artifactId>UltimateDrugs</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/UltimateDrugs.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.willfp</groupId>
            <artifactId>EcoPets</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/EcoPets_v2.18.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>qu.moon</groupId>
            <artifactId>TabList</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/dwaslashe-Tablist-1.0-stable.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>g.sit</groupId>
            <artifactId>GSit</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/GSit-1.4.12.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>blockParticles</groupId>
            <artifactId>blockParticles</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/BlockParticles.v1.11.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>Duels</groupId>
            <artifactId>pluginduels</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/Duels-3.5.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>Vehicles</groupId>
            <artifactId>pluginvehicles</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/OneDrive/Pulpit/IntelliJ Projects/dwaslashe-SurvivalCore/libs/Vehicles(14.1).jar</systemPath>
        </dependency>
        <!--
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>5.0.0-alpha.20</version>
        </dependency>
        -->


        <!--
        API paper and spigot
        -->

        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.20.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.20.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>plugin-annotations</artifactId>
            <version>1.2.3-SNAPSHOT</version>
        </dependency>

        <!--
        Okaeri
        -->

        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-pluralize</artifactId>
            <version>1.1.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-configs-yaml-bukkit</artifactId>
            <version>3.4.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-configs-yaml-snakeyaml</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-configs-serdes-bukkit</artifactId>
            <version>3.2.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-configs-core</artifactId>
            <version>3.4.2</version>
            <scope>compile</scope>
        </dependency>

        <!--
        Assist
        -->

        <dependency>
            <groupId>com.github.brcdev-minecraft</groupId>
            <artifactId>shopgui-api</artifactId>
            <version>3.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.decentsoftware-eu</groupId>
            <artifactId>decentholograms</artifactId>
            <version>2.8.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>brigadier</artifactId>
            <version>1.0.18</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>4.0.3</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>xyz.upperlevel.spigot.book</groupId>
            <artifactId>spigot-book-api</artifactId>
            <version>1.6</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.30</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>3.29.2-GA</version>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.10.2</version>
        </dependency>
        <dependency>
            <groupId>de.themoep</groupId>
            <artifactId>minedown</artifactId>
            <version>1.7.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <!--
        Plugins
        -->

        <dependency>
            <groupId>org.maxgamer</groupId>
            <artifactId>QuickShop</artifactId>
            <version>5.1.2.5</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.gitlab.ruany</groupId>
            <artifactId>LiteBansAPI</artifactId>
            <version>0.4.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.neznamy</groupId>
            <artifactId>tab-api</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.sk89q.worldguard</groupId>
            <artifactId>worldguard-bukkit</artifactId>
            <version>7.0.6</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.luckperms</groupId>
            <artifactId>api</artifactId>
            <version>5.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.5</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <dependencyReducedPomLocation>
                                ${project.build.directory}/dependency-reduced-pom.xml
                            </dependencyReducedPomLocation>
                            <relocations>
                                <relocation>
                                    <pattern>eu.okaeri.configs</pattern>
                                    <shadedPattern>xyz.dwaslashe.libs.eu.okaeri.configs</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>eu.okaeri.pluralize</pattern>
                                    <shadedPattern>xyz.dwaslashe.libs.eu.okaeri.pluralize</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.zaxxer.hikari</pattern>
                                    <shadedPattern>xyz.dwaslashe.libs.zaxxer.hikari</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>de.tr7zw.changeme.nbtapi</pattern>
                                    <shadedPattern>xyz.dwaslashe.libs.changeme.nbtapi</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>de.themoep.minedown</pattern>
                                    <shadedPattern>xyz.dwaslashe.libs.minedown</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>