main: xyz.dwaslashe.survivalcore.Main
name: dwaslashe-SurvivalCore
version: 1.0.0
author: [dwaslashe]
website: dwaslashe.xyz
description: Core for Servers Survival
api-version: 1.18
depend:
  - Vault
  - LuckPerms
  - TAB
softdepend:
  - PlaceholderAPI