main: xyz.dwaslashe.survivalcore.Main
name: dwaslashe-SurvivalCore
version: 1.0.0
authors: [dwaslashe, Mebrigji]
website: dwaslashe.xyz
description: Core for Servers Survival
api-version: 1.19
loadbefore:
  - WorldGuard
depend:
  - Multiverse-Core
  - Vault
  - LuckPerms
  - TAB
  - NBTAPI
  - SA-Economy
  - minePlots
  - dwaslashe-TabList
  - LuckPerms
  - q1zZ-DiscordRewards
softdepend:
  - Duels
  - ItemsAdder
  - PlaceholderAPI
#  - WGRegionEvents
  - WorldGuard
commands:
  sb: